### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by Star-Cyber3**

### CODE REVIEW

**Comment by AmjadNoor** [comment]
Please I request you to make your code neat and clean.

**Comment by Star-Cyber3** [comment]
Is it not?

**Comment by AmjadNoor** [comment]
Close this pull request.

**Comment by Star-Cyber3** [comment]
Do you want me to merge

**Comment by Star-Cyber3** [comment]
The code is not what I want.  If you delete one item right now, the clear all button is greyed, so if you have twenty items and delete one, but want to delete all after, that option is unavailable.

**Comment by AmjadNoor** [comment]
Close this pull request when I am done then I generate pull request.

**Comment by Star-Cyber3** [comment]
#15

**Pull request closed without merging**
